### ISSUE TITLE
/opt/ssh_populate.sh: no such file or directory

### ISSUE THREAD

**Issue by jason-instacart** [joshuamkite/terraform-aws-ssh-bastion-service#25] opened 2019-01-29 22:27 UTC
Hi, we have successfully deployed this module in the past. Now we are on the latest version (4.5.1). After deployment, whenever I run `ssh -v xxxxxx@host`, I got this error. Any ideas? Thanks!

`OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/xxxxx/.ssh/config
debug1: /Users/xxxxx/.ssh/config line 1: Applying options for *
debug1: /Users/xxxxx/.ssh/config line 6: Applying options for *.amazonaws.com
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to xxxxxxxx.elb.us-east-1.amazonaws.com port 22.
debug1: Connection established.
debug1: identity file /Users/xxxxx/.ssh/id_rsa type 0
debug1: identity file /Users/xxxxx/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: ssh_exchange_identification: /usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \\"/opt/ssh_populate.sh\\": stat /opt/ssh_populate.sh: no such file or directory": unknown.

ssh_exchange_identification: Connection closed by remote host`

**Comment by joshuamkite** [comment] 2019-01-29 23:39
Hi

I don't have your full config to review but the error you have given seems to be generated by docker itself. The code in user data here  has not changed for 4 months. This also suggests that the problem is not directly with this code. The user-data populated via `user_data/docker_setup.tpl` installs the latest version of `docker-ce` directly from docker.com. Googling `"OCI runtime create failed: container_linux.go:344:"` Show a numsber of similar issues, notably [this post](https://github.com/docker/for-linux/issues/561) referencing [this thread](https://github.com/moby/moby/issues/38174). These seem to relate to changes arising in docker 18.09. I see that according to the [upstream changelog](https://docs.docker.com/engine/release-notes/) Docker 18.09.0 was released 2018-11-08 and 18.0.9.0 on 2019-01-09. I see the following on that page:

> 
> **IMPORTANT NOTES ABOUT THIS RELEASE**
>
> In Docker versions prior to 18.09, containerd was managed by the Docker engine daemon. In Docker Engine 18.09, containerd is managed by systemd. Since containerd is managed by systemd, any custom configuration to the `docker.service` systemd configuration which changes mount settings (for example, `MountFlags=slave`) breaks interactions between the Docker Engine daemon and containerd, and you will not be able to start containers.
> 
> Run the following command to get the current value of the `MountFlags` property for the `docker.service`:
> 
>     sudo systemctl show --property=MountFlags docker.service
>     MountFlags=
> 
> Update your configuration if this command prints a non-empty value for `MountFlags`, and restart the docker service.
> 

Since in this module the binaries and scripts are mounted from a shared volume on the host, it would seem likely that this change is what is breaking things. 

Although pull requests are always welcome, I am afraid it will likely be a few days before I can properly investigate and fix this myself. Meantime I would suggest either pursuing the above or, in the short term, replacing the code in user_data/docker_setup.tpl with similar code but specifying a version prior to 18.09 on line 7. You should be able to do this via extra-user-data if you don't want to change the module code directly.

Thanks for flagging this, it will need to be fixed

**Comment by jason-instacart** [comment] 2019-01-29 23:46
Thanks for the speedy reply! We will try to find a short term workaround. I am leaving this issue open for now.

**Comment by KevinGreen** [comment] 2019-01-29 23:50
I just checked on an instance showing the same behaviour and the file was never written to /opt/iam_helper/ssh_populate.sh due to this error:
```/var/lib/cloud/instance/scripts/module_ssh_populate_same_account: line 3: $ + 1 : syntax error: operand expected (error token is "$ + 1 ")```

**Comment by KevinGreen** [comment] 2019-01-30 01:13
Hey @joshuamkite, I'm also at Instacart so I was looking into the same issue. This PR (https://github.com/joshuamkite/terraform-aws-ssh-bastion-service/pull/26) fixes the issue for our deployment. I can't explain exactly why this was causing a problem all of a sudden though

**Comment by joshuamkite** [comment] 2019-01-30 01:19
@jason-instacart I need to ask you for some more information about your config.

I have just tried a test deployment of the current version module as a standalone plan and I do not get this behaviour. I get the following:

    OpenSSH_7.9p1, LibreSSL 2.7.3
    debug1: Reading configuration data /Users/xxxxx/.ssh/config
    debug1: /Users/xxxxx/.ssh/config line 1: Applying options for *
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 48: Applying options for *
    debug1: Connecting to xxxxx port22.
    debug1: Connection established.
    debug1: identity file /Users/xxxxx/.ssh/xxxxx-xxxxx-rsa type 0
    debug1: identity file /Users/xxxxx/.ssh/xxxxx-xxxxx-rsa-cert type -1
    debug1: Local version string SSH-2.0-OpenSSH_7.9
    debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.1
    debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.1 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat0x04000002
    debug1: Authenticating to xxxxx:22 as 'xxxxx'
    debug1: SSH2_MSG_KEXINIT sent
    debug1: SSH2_MSG_KEXINIT received
    debug1: kex: algorithm: curve25519-sha256
    debug1: kex: host key algorithm: ecdsa-sha2-nistp256
    debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    debug1: Server host key: ecdsa-sha2-nistp256 SHA256:xxxxx
    The authenticity of host 'xxxxx (xxxxx)' can't be established.
    ECDSA key fingerprint is SHA256:xxxxx.
    Are you sure you want to continue connecting (yes/no)? yes
    Warning: Permanently added 'xxxxx,xxxxx' (ECDSA) to the list of known hosts.
    debug1: rekey after 134217728 blocks
    debug1: SSH2_MSG_NEWKEYS sent
    debug1: expecting SSH2_MSG_NEWKEYS
    debug1: SSH2_MSG_NEWKEYS received
    debug1: rekey after 134217728 blocks
    debug1: Will attempt key: /Users/xxxxx/.ssh/xxxxx-xxxxx-rsa RSASHA256:xxxx explicit agent
    debug1: Will attempt key: /Users/xxxxx/.ssh/joshuamkite_private_github_rsaRSA SHA256:xxxx agent
    debug1: SSH2_MSG_EXT_INFO received
    debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
    debug1: SSH2_MSG_SERVICE_ACCEPT received
    debug1: Authentications that can continue: publickey,password
    debug1: Next authentication method: publickey
    debug1: Offering public key: /Users/xxxxx/.ssh/xxxxx-xxxxx-rsa RSA SHA256:xxxxx explicit agent
    debug1: Server accepts key: /Users/xxxxx/.ssh/xxxxx-xxxxx-rsa RSA SHA256:xxxxx explicit agent
    debug1: Authentication succeeded (publickey).
    Authenticated to xxxxx ([xxxxx]:22).
    debug1: channel 0: new [client-session]
    debug1: Requesting no-more-sessions@openssh.com
    debug1: Entering interactive session.
    debug1: pledge: network
    debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
    debug1: Sending environment.
    debug1: Sending env LANG = en_GB.UTF-8
    Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.9.0-8-amd64 x86_64)

And logging on to the host I get

    Linux xxxx 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64

and

`admin@xxxx:~$ docker -v`
`Docker version 18.09.1, build 4c52b90`

**Comment by joshuamkite** [comment] 2019-01-30 01:22
@KevinGreen Understood! Thanks for P/R. It's late here. I will review in the morning, it's late here!

**Comment by jason-instacart** [comment] 2019-01-30 22:01
@joshuamkite this is how we call the module:

`module "ssh-bastion-service" {
  source  = "joshuamkite/ssh-bastion-service/aws"
  version = "4.5.1"

  aws_profile = "default"
  aws_region  = "${var.region}"
  vpc         = "${data.terraform_remote_state.vpc.vpc_id}"
  subnets_lb  = "${data.terraform_remote_state.vpc.private_subnets}"
  subnets_asg = "${data.terraform_remote_state.vpc.private_subnets}"

  cidr_blocks_whitelist_service = [
    "10.xxx.xx0.0/24",
    "10.xxx.xx1.0/24",
    "10.xxx.xx2.0/24",
    "10.xxx.xx3.0/24",
  ]
  bastion_instance_type         = "t2.medium"
  bastion_service_host_key_name = "${var.ec2_keypair}"
  environment_name              = "${var.environment}"
  lb_is_internal                = true
}`

**Comment by f-dg** [comment] 2019-01-31 18:57
Bumped on the same issue. I'm running on ubuntu 16.04 and Docker 18.09.1. My container can't execute any commands, it falls with error:

`OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"ping\": executable file not found in $PATH": unknown`

Docker.service 

[Unit] 
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
BindsTo=containerd.service
After=network-online.target firewalld.service
Wants=network-online.target
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/dockerd -H fd://
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always

StartLimitBurst=3


StartLimitInterval=60s

LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

TasksMax=infinity

Delegate=yes

KillMode=process

[Install]
WantedBy=multi-user.target

There's no MountFlags, but `systemctl show --property=MountFlags docker.service` shows
`MountFlags=0`

Also I don't have another config in /etc/systemd/system/docker.service.d
Have any ideas what is wrong ?

**Comment by joshuamkite** [comment] 2019-01-31 23:57
Thanks everyone for the feedback and @kevingreen for the pull request which I have now merged as the only code change for release 4.6. @jason-instacart ; @f-dg does this release fix your issues? I am not sure but the detailed theory above re new version of Docker may not have been the problem after all!

**Comment by joshuamkite** [comment] 2019-02-06 22:11
@f-dg I haven't heard from you in a week. If I have not heard from you by 14 Feb then I will be closing this issue as it is presumably fixed

**Comment by joshuamkite** [comment] 2019-02-16 23:47
Closing as already fixed/ no further info

**Closed by joshuamkite** 2019-02-16 23:47 UTC
Labels: already fixed?, question
